### ISSUE TITLE
스크랩 리스트에서 룸 클릭시 흰 화면만 뜨는 오류를 수정한다

### ISSUE THREAD

**Issue by DYGames** [woowacourse-teams/2023-diggin-room#250]
### 버그 설명

- [x] 스크랩 리스트에서 룸 클릭시 흰 화면만 뜨는 오류
- [x] 소리가 재생되지 않는 오류
- [x] 마지막 룸 도달시 더 이상 스크롤 되지 않도록
- [x] 0번째, 마지막 + 1번째 다른 룸 표시되는 오류
- [x] 다른 액티비티 갔을 때 재생되는 오류
